compile1:
	gcc -Wall sample_program1.c -o sample1.out

run1:
	./sample1.out

compile2:
	gcc -Wall -pthread sample_program2.c -o sample2.out

run2:
	./sample2.out

compile3:
	gcc -Wall -pthread sample_program3.c -o sample3.out

run3:
	./sample3.out
	
compile:
	gcc -Wall -pthread fileserver.c -o main.out

run:
	./main.out

clean:
	rm *.out
	echo 'Cleaning done'

