compile1:
	gcc -Wall sample_program1.c -o sample1.out

run1:
	./sample1.out
	
compile1Mod:
	gcc -Wall sample_program1_modified.c -o sample1_modified.out

run1Mod:
	./sample1_modified.out
	
compileReader:
	gcc -Wall reader_shm.c -o reader.out

runReader:
	./reader.out
	
compileWriter:
	gcc -Wall writer_shm.c -o writer.out

runWriter:
	./writer.out

clean:
	rm *.out
	echo 'Cleaning done'
