compile1:
	gcc -Wall sample_program1.c -o sample1.out

run1:
	./sample1.out
	
compile1Mod:
	gcc -Wall sample_program1_modified.c -o sample1_modified.out

run1Mod:
	./sample1_modified.out
	
compile:
	gcc -Wall fileserver.c -o main.out

run:
	./main.out

clean:
	rm *.out
	echo 'Cleaning done'
