compile1:
	gcc -Wall sample_program1.c -o sample1.out

run1:
	./sample1.out

compile2:
	gcc -Wall sample_program2.c -o sample2.out

run2:
	./sample2.out

compile:
	gcc -Wall communicating_processes.c -o main.out

run:
	./main.out

clean:
	rm *.out
	echo 'Cleaning done'

